/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static jdk.nashorn.internal.objects.NativeArray.map;
import static project.AdminOk.myMap;
import static project.MainWindow.myMap;
import static project.NewUser.myMap;


/**
 *
 * @author root
 */
public class Menu extends javax.swing.JFrame {
    public static HashMap<String, LinkedList<String>> myMap = new HashMap<>();
    public String Tid;
    public String tableID;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
   
    public void setID(){
        Tid=tableID;  
    }
    
    public String getID(){
        return Tid;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Παρακαλώ επιλέξτε ");

        jButton1.setText("Επόμενο");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Γεύμα 1", "Γεύμα 2", "Γεύμα 3", "Γεύμα 4", "Ποτό 1", "Ποτό 2", "Ποτό 3", "Ποτό 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Τέλος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Table's ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        String item;
        Integer amount;
        Integer price;
        Integer total;
        tableID=jTextField1.getText();
        item =  jComboBox1.getSelectedItem().toString();
        amount = (Integer) jSpinner2.getValue();
        
        if(item=="Γεύμα 1"){
            price=30;
        }
        else if(item=="Γεύμα 2"){
             price=40;
        }
        else if(item=="Γεύμα 3"){
              price=15;
        }
        else if(item=="Γεύμα 4"){
             price=20;
        }
        else if(item=="Ποτό 1"){
             price=10;
        }
        
        else if(item=="Ποτό 2"){
             price=15;
        }
        else if(item=="Ποτό 3"){
             price=8;
        }
        else{
             price=14;
        }
       
        total=amount*price;
        
        
        
                try {
                    
                    String str = "\n" + tableID + "," + item + "," + amount + "," + price + "," + total ;
                    Files.write(Paths.get("./src/project/Tables"), str.getBytes(), StandardOpenOption.APPEND);
                    String cookstr = "\n" + tableID + "," + item + "," + amount + "," ;
                    Files.write(Paths.get("./src/project/ToCook"), cookstr.getBytes(), StandardOpenOption.APPEND);
                    JOptionPane.showMessageDialog(null, "Added succesfully");
                    this.setVisible(false);
                }  catch (IOException ex) {
                    Logger.getLogger(Waiter.class.getName()).log(Level.SEVERE, null, ex);
                }
                
          
        
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String item;
        Integer amount;
        Integer price;
        Integer total;
        tableID=jTextField1.getText();
        item =  jComboBox1.getSelectedItem().toString();
        amount = (Integer) jSpinner2.getValue();
        if(amount!=0){
            if(item=="Γεύμα 1"){
                price=30;
            }
            else if(item=="Γεύμα 2"){
                 price=40;
            }
            else if(item=="Γεύμα 3"){
                  price=15;
            }
            else if(item=="Γεύμα 4"){
                 price=20;
            }
            else if(item=="Ποτό 1"){
                 price=10;
            }

            else if(item=="Ποτό 2"){
                 price=15;
            }
            else if(item=="Ποτό 3"){
                 price=8;
            }
            else{
                 price=14;
            }

            total=amount*price;



                    try {

                        String str = "\n" + tableID + "," + item + "," + amount + "," + price + "," + total ;
                        Files.write(Paths.get("./src/project/Tables"), str.getBytes(), StandardOpenOption.APPEND);
                        String cookstr = "\n" + tableID + "," + item + "," + amount ;
                        Files.write(Paths.get("./src/project/ToCook"), cookstr.getBytes(), StandardOpenOption.APPEND);
                        JOptionPane.showMessageDialog(null, "Added succesfully");
                        this.setVisible(false);
                    }  catch (IOException ex) {
                        Logger.getLogger(Waiter.class.getName()).log(Level.SEVERE, null, ex);
                }
        }  
        
       Waiter w = new Waiter();
       w.setVisible(true);
       this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed
   
 
     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
